### ISSUE TITLE
Missing resource: buffer.bin

### ISSUE THREAD

**Issue by mateuszwojt** [V-Sekai/FBX2glTF#10]
I converted a simple cube model into glTF format with the latest version of the converter. When I try to load it in Blender, it throws an error: `Missing resource, 'buffer.bin'`. When I look into models converted to glTF with Blender, they typically have the buffers encoded as URI, i.e.
```
 "buffers" : [
        {
            "byteLength" : 4587280,
            "uri" : "data:application/octet-stream;base64,..."
```

Is this a bug?

Edit:
By the way - I checked it with GLB and I can load assets converted to the binary format.

**Comment by fire** [comment]
There are three ways to encode a gltf.

1. .glb
2. .gltf + .bin
3. .gltf (embedded) This is the rarest and not recommended.

What commands are you running?

**Comment by fire** [comment]
Are you able to provide some more information?

**Comment by fire** [comment]
I think you fixed this, I can't tell. Let me know if I interpreted wrongly.
