### ISSUE TITLE
Investigate removing dependency on MSVC redistributable on Windows

### ISSUE THREAD

**Issue by Calinou** [V-Sekai/FBX2glTF#11]
The README says:

> FBX2glTF.exe is for Windows. REQUIRES MVSC redistributable on Windows https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads

We should investigate removing this requirement to make installation easier, especially in automated scenarios. I see two ways to do this:

- Link against the GNU ABI by building using MinGW using either GCC or [Clang](https://github.com/mstorsjo/llvm-mingw). This is what official Godot binaries do. This makes binaries slightly larger, but it's probably not much of an issue here. However, fbx2gltf may not build with MinGW out of the box, and the FBX SDK may not be compatible with this either.
- Link against the built-in Windows C++ runtime. This runtime is only present on Windows 10 and 11. Therefore, this would bump the baseline Windows support to Windows 10, but I don't think a whole lot of people will be using Godot 4.x *and* FBX import on older Windows versions by the time Godot 4.0 is released. This shouldn't increase binary size by a noticeable margin.

Godot itself does not require the MSVC redistributable installed, so it would be good to not have fbx2gltf require it either.

Of course, the above points are moot if the FBX SDK itself requires the MSVC redistributable with no way to work around this.

For now, the README should mention the MSVC redistributable version that is expected by the executable, as newer redistributables are *not* compatible with executables linked against older versions (and vice versa). Is fbx2gltf built with MSVC 2019 or 2022 on GitHub Actions?

**Comment by fire** [comment]
> The FBX SDK itself requires the MSVC redistributable with no way to work around this.

I think this is the problem.

**Comment by fire** [comment]
```
jobs:
  build-win-10:
    runs-on: windows-2019
```

Here's what it is from CICD.

**Comment by fire** [comment]
I don't have any good approaches for this. Will close. Comment if you have an idea.
