### ISSUE TITLE
Animation export broken compared to original FBX2glTF

### ISSUE THREAD

**Issue by DavidRobb** [V-Sekai/FBX2glTF#16]
Animation of this leg is distorted when converted to glTF using this release
[MaleLeg_Test_Export_24_05_22.zip](https://github.com/V-Sekai/FBX2glTF/files/8764392/MaleLeg_Test_Export_24_05_22.zip)
F

**Comment by fire** [comment]
Can reproduce.

![image](https://user-images.githubusercontent.com/32321/187048432-778980bb-2032-44a7-8613-413e65e7293d.png)
